language: scala

sudo: true

git:
  depth: 1

scala:
  - "2.12.4"

jdk:
  - openjdk11

services:
  - docker

before_install:
  - sudo apt-get install wget curl
  - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash 
  - export NVM_DIR="/home/travis/.nvm" 
  - sh $NVM_DIR/nvm.sh
  - nvm install 13.1.0 
  - nvm use 13.1.0 
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  #- wget --quiet https://sh.rustup.rs -O rustupinstall.sh
  #- sh ./rustupinstall.sh -y
  #- export PATH=$PATH:$HOME/.cargo/bin
  #- rustup update
  #- rustup default stable 
  - docker-compose -f scripts/docker-compose-test.yml up -d
  
script:
  - sh ./scripts/build.sh all
  # - sh ./scripts/upload.sh

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.nvm
    - $HOME/.yarn
    - $HOME/.yarn-cache

