[package]
name = "@@PLUGIN_NAME@@"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
extism-pdk = "0.1.1"
serde = "1.0.152"
serde_json = "1.0.91"

[lib]
crate_type = ["cdylib"]
path = "./lib.rs"
