apiVersion: v3
name: otoroshi
description: An Otoroshi based Kubernetes ingress controller
type: application
version: 17.10.0-dev
appVersion: 17.10.0-dev
keywords:
  - otoroshi
  - ingress
  - reverseproxy
  - apimanager
sources:
  - https://github.com/MAIF/otoroshi
maintainers:
  - name: mathieuancelin
icon: https://raw.githubusercontent.com/MAIF/otoroshi/master/resources/otoroshi-logo.png
dependencies:
  - name: redis
    version: "21.2.9"
    repository: "https://charts.bitnami.com/bitnami"
    condition: global.prod