apiVersion: v3
name: otoroshi
description: An Otoroshi based Kubernetes ingress controller
type: application
version: 1.0.0
appVersion: 1.5.0-alpha.16
keywords:
  - otoroshi
  - ingress
  - reverseproxy
  - apimanager
sources:
  - https://github.com/MAIF/otoroshi
maintainers:
  - name: mathieuancelin
icon: https://raw.githubusercontent.com/MAIF/otoroshi/master/resources/otoroshi-logo.png
dependencies:
  - name: redis
    version: "11.2.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: global.prod