---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "service-groups.proxy.otoroshi.io"
  creationTimestamp: null
spec:
  group: "proxy.otoroshi.io"
  names:
    kind: "ServiceGroup"
    plural: "service-groups"
    singular: "service-group"
  scope: "Namespaced"
  versions:
  - name: "v1alpha1"
    served: true
    storage: false
    deprecated: true
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
        type: "object"
        properties:
          spec:
            type: "object"
  - name: "v1"
    served: true
    storage: true
    deprecated: false
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
        type: "object"
        properties:
          spec:
            type: "object"
---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "organizations.proxy.otoroshi.io"
  creationTimestamp: null
spec:
  group: "proxy.otoroshi.io"
  names:
    kind: "Organization"
    plural: "organizations"
    singular: "organization"
  scope: "Namespaced"
  versions:
  - name: "v1alpha1"
    served: true
    storage: false
    deprecated: true
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
        type: "object"
        properties:
          spec:
            type: "object"
  - name: "v1"
    served: true
    storage: true
    deprecated: false
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
        type: "object"
        properties:
          spec:
            type: "object"
---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "teams.proxy.otoroshi.io"
  creationTimestamp: null
spec:
  group: "proxy.otoroshi.io"
  names:
    kind: "Team"
    plural: "teams"
    singular: "team"
  scope: "Namespaced"
  versions:
  - name: "v1alpha1"
    served: true
    storage: false
    deprecated: true
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
        type: "object"
        properties:
          spec:
            type: "object"
  - name: "v1"
    served: true
    storage: true
    deprecated: false
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
        type: "object"
        properties:
          spec:
            type: "object"
---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "service-descriptors.proxy.otoroshi.io"
  creationTimestamp: null
spec:
  group: "proxy.otoroshi.io"
  names:
    kind: "ServiceDescriptor"
    plural: "service-descriptors"
    singular: "service-descriptor"
  scope: "Namespaced"
  versions:
  - name: "v1alpha1"
    served: true
    storage: false
    deprecated: true
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
        type: "object"
        properties:
          spec:
            type: "object"
  - name: "v1"
    served: true
    storage: true
    deprecated: false
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
        type: "object"
        properties:
          spec:
            type: "object"
---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "apikeys.proxy.otoroshi.io"
  creationTimestamp: null
spec:
  group: "proxy.otoroshi.io"
  names:
    kind: "ApiKey"
    plural: "apikeys"
    singular: "apikey"
  scope: "Namespaced"
  versions:
  - name: "v1alpha1"
    served: true
    storage: false
    deprecated: true
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
        type: "object"
        properties:
          spec:
            type: "object"
  - name: "v1"
    served: true
    storage: true
    deprecated: false
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
        type: "object"
        properties:
          spec:
            type: "object"
---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "certificates.proxy.otoroshi.io"
  creationTimestamp: null
spec:
  group: "proxy.otoroshi.io"
  names:
    kind: "Certificate"
    plural: "certificates"
    singular: "certificate"
  scope: "Namespaced"
  versions:
  - name: "v1alpha1"
    served: true
    storage: false
    deprecated: true
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
        type: "object"
        properties:
          spec:
            type: "object"
  - name: "v1"
    served: true
    storage: true
    deprecated: false
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
        type: "object"
        properties:
          spec:
            type: "object"
---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "global-configs.proxy.otoroshi.io"
  creationTimestamp: null
spec:
  group: "proxy.otoroshi.io"
  names:
    kind: "GlobalConfig"
    plural: "global-configs"
    singular: "global-config"
  scope: "Namespaced"
  versions:
  - name: "v1alpha1"
    served: true
    storage: false
    deprecated: true
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
        type: "object"
        properties:
          spec:
            type: "object"
  - name: "v1"
    served: true
    storage: true
    deprecated: false
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
        type: "object"
        properties:
          spec:
            type: "object"
---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "jwt-verifiers.proxy.otoroshi.io"
  creationTimestamp: null
spec:
  group: "proxy.otoroshi.io"
  names:
    kind: "JwtVerifier"
    plural: "jwt-verifiers"
    singular: "jwt-verifier"
  scope: "Namespaced"
  versions:
  - name: "v1alpha1"
    served: true
    storage: false
    deprecated: true
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
        type: "object"
        properties:
          spec:
            type: "object"
  - name: "v1"
    served: true
    storage: true
    deprecated: false
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
        type: "object"
        properties:
          spec:
            type: "object"
---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "auth-modules.proxy.otoroshi.io"
  creationTimestamp: null
spec:
  group: "proxy.otoroshi.io"
  names:
    kind: "AuthModule"
    plural: "auth-modules"
    singular: "auth-module"
  scope: "Namespaced"
  versions:
  - name: "v1alpha1"
    served: true
    storage: false
    deprecated: true
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
        type: "object"
        properties:
          spec:
            type: "object"
  - name: "v1"
    served: true
    storage: true
    deprecated: false
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
        type: "object"
        properties:
          spec:
            type: "object"
---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "scripts.proxy.otoroshi.io"
  creationTimestamp: null
spec:
  group: "proxy.otoroshi.io"
  names:
    kind: "Script"
    plural: "scripts"
    singular: "script"
  scope: "Namespaced"
  versions:
  - name: "v1alpha1"
    served: true
    storage: false
    deprecated: true
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
        type: "object"
        properties:
          spec:
            type: "object"
  - name: "v1"
    served: true
    storage: true
    deprecated: false
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
        type: "object"
        properties:
          spec:
            type: "object"
---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "tcp-services.proxy.otoroshi.io"
  creationTimestamp: null
spec:
  group: "proxy.otoroshi.io"
  names:
    kind: "TcpService"
    plural: "tcp-services"
    singular: "tcp-service"
  scope: "Namespaced"
  versions:
  - name: "v1alpha1"
    served: true
    storage: false
    deprecated: true
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
        type: "object"
        properties:
          spec:
            type: "object"
  - name: "v1"
    served: true
    storage: true
    deprecated: false
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
        type: "object"
        properties:
          spec:
            type: "object"
---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "data-exporters.proxy.otoroshi.io"
  creationTimestamp: null
spec:
  group: "proxy.otoroshi.io"
  names:
    kind: "DataExporter"
    plural: "data-exporters"
    singular: "data-exporter"
  scope: "Namespaced"
  versions:
  - name: "v1alpha1"
    served: true
    storage: false
    deprecated: true
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
        type: "object"
        properties:
          spec:
            type: "object"
  - name: "v1"
    served: true
    storage: true
    deprecated: false
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
        type: "object"
        properties:
          spec:
            type: "object"
---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "admins.proxy.otoroshi.io"
  creationTimestamp: null
spec:
  group: "proxy.otoroshi.io"
  names:
    kind: "Admin"
    plural: "admins"
    singular: "admin"
  scope: "Namespaced"
  versions:
  - name: "v1alpha1"
    served: true
    storage: false
    deprecated: true
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
        type: "object"
        properties:
          spec:
            type: "object"
  - name: "v1"
    served: true
    storage: true
    deprecated: false
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
        type: "object"
        properties:
          spec:
            type: "object"
